### ISSUE TITLE
Alt Attribute

### ISSUE THREAD

**Issue by jim-rosales** [AwesomeAartvark/prj-rev-bwfs-dasmoto#1]
Excellent job adding an alt attribute on all your images! 

It beneficial to include the attribute for several reasons:
1. It increases the [accessibility](https://www.codecademy.com/articles/accessibility) of your site. 
2. The attribute is used as a backup, in case the image cannot be rendered. 
3.  Optimizes your site for search engine results.

https://github.com/AwesomeAartvark/prj-rev-bwfs-dasmoto/blob/34a7e3bb49e26733ec6c4d20800642d84a36142c/DasmotosArts%26Crafts/index.html#L14

**Comment by AwesomeAartvark** [comment]
Thank you! The alt attribute was something I didn't really know about, so I'm glad I was able to apply it correctly!
