### ISSUE TITLE
Span Use

### ISSUE THREAD

**Issue by jim-rosales** [AwesomeAartvark/prj-rev-bwfs-dasmoto#2]
Nice job using the span element to apply the required blue color for all your prices!

https://github.com/AwesomeAartvark/prj-rev-bwfs-dasmoto/blob/34a7e3bb49e26733ec6c4d20800642d84a36142c/DasmotosArts%26Crafts/css/stylesheet.css#L21-L23

**Comment by AwesomeAartvark** [comment]
Thank you!
