### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [AwesomeAartvark/prj-rev-bwfs-dasmoto#4]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4
* _Comment(s):_ All files were linked correctly
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4
* _Comment(s):_ All required specifications were implemented
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4
* _Comment(s):_ All HTML elements were correctly used
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4
* _Comment(s):_ All CSS rules were applied using best practices
 
### Overall Score: 16/16

Congrats on finishing the Dasmoto project! Overall you did an incredible job implementing all the required styles while following best practices. Your stylesheet was impeccable as well I didn't see any duplicate styles, and you did a nice job laying out your HTML code. 

The only area I felt your code could improve on was by making use comments for both your files. For this considering looking over this sample [HTML](https://gist.github.com/jim-rosales/c1446e66054c97071406610be771fa79) solution and seeing how comments were added throughout the file. Feel free to also look over this sample [CSS](https://gist.github.com/jim-rosales/2f5cfda50385ffddc1225f0e8a9f4807) solution to get an idea of the type of comments you can leave on your stylesheet next time as well.

If you'd like to continue practicing consider researching the [position](https://developer.mozilla.org/en-US/docs/Web/CSS/position) property along with the sticky value that is usually used to create a menu bar that sticks to the top of the page when you scroll down. This property might be something you could use on upcoming projects!

**Comment by AwesomeAartvark** [comment]
Thank you for all your feedback, I appreciate it! I completely forgot about commenting, but that is definitely a very important part, especially when I start creating larger projects, so thank you for reminding me! And I have heard of the position property, but a refresher will be very helpful. Thanks again!
